name: nosmai_effects_sdk
description: Official Flutter plugin for real-time Nosmai AR effects, beauty filters, backgrounds, interactive camera games, capture, and cloud filters.
version: 1.0.1
homepage: https://nosmai.com
repository: https://github.com/nosmai/nosmai_effects_sdk_flutter
documentation: https://nosmai.com/docs/effects/installation/flutter/
issue_tracker: https://github.com/nosmai/nosmai_effects_sdk_flutter/issues

topics:
  - augmented-reality
  - beauty
  - camera
  - effects
  - filters

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.nosmai.nosmai_flutter
        pluginClass: NosmaiFlutterPlugin
      ios:
        pluginClass: NosmaiFlutterPlugin
